# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = DP_XO
DESTDIR = ../x64/Debug
CONFIG += debug
CONFIG += console
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles

FORMS += \
    GameWindow.ui

HEADERS += \
    GameWindow.h

SOURCES += \
    GameWindow.cpp
